server:
  port: ${PORT:8084}
spring:
  data:
    mongodb:
      database: transactions_db
      port: ${MONGO_PORT:27017}
      host: ${MONGO_HOST:localhost}
      username: ${MONGO_USER:team-d}
      password: ${MONGO_PWD:jboss-team-d}
  application:
    name: transaction
  cloud:
    stream:
      kafka:
        binder:
          brokers:
            - ${KAFKA_BROKER:localhost}


security:
  oauth2:
    resource:
      access-token-uri: ${AUTHORIZATION_HOST:http://localhost:9191}/oauth/token
      token-info-uri: ${AUTHORIZATION_HOST:http://localhost:9191}/oauth/check_token
    client:
      client-id: mobile
      client-secret: pin
service.bankaccount: ${BANKACCOUNT_HOST:http://localhost:8083/}

axon:
  eventhandling:
    processors:
      name:
        mode: subscribing
#        source: eventbus


