server:
  port: ${PORT:8084}
spring:
  data:
    mongodb:
      database: transactions_db
      port: 27017
      host: localhost
  application:
    name: profile
  cloud:
    stream:
      kafka:
        binder:
          brokers:
            - ${KAFKA_BROKER:localhost}
security:
  oauth2:
    resource:
      access-token-uri: http://${AUTHORIZATION_HOST:localhost}:9191/oauth/token
      token-info-uri: http://${AUTHORIZATION_HOST:localhost}:9191/oauth/check_token
    client:
      client-id: mobile
      client-secret: pin
service.bankaccount: ${SERVICE_BANKACCOUNT:http://localhost:8083/}
